---
apiVersion: v1
kind: Service
metadata:
  name: ubiquity
  labels:
    app: ubiquity
spec:
  ports:
    - nodePort: 31999
      port: 9999
      protocol: TCP
      targetPort: 9999
  type: NodePort
  selector:
    app: ubiquity
---
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: ubiquity
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubiquity
    spec:
      containers:
      - name: ubiquity
        image: midoblgsm/ubiquity
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
          name: ubiquity-port
        env:
          - name: PORT             # Ubiquity port
            value: "9999"
          - name: LOG_PATH         # Ubiquity log file directory
            value: "/tmp"
          - name: CONFIG_PATH         # Ubiquity config directory
            value: "/tmp/ubiquity"
          - name: DEFAULT_BACKEND  # or other backends, such as :scbe, spectrum-scale-nfs
            value: "spectrum-scale"
          - name: LOG_LEVEL       # debug / info / error
            value: "info"
          - name: DEFAULT_FILESYSTEM_NAME
            value: "gold"
          - name: SSC_NFS_SERVER_ADDRESS
            value: "127.0.0.1"
          - name: SSC_SSH_HOST
            value: "192.168.10.10"
          - name: SSC_SSH_PORT
            value: "22"
          - name: SSC_SSH_USER
            value: "ubiquity"
          - name: FORCE_DELETE
            value: "false"
          - name: SCBE_DEFAULT_SERVICE
            value: "gold"
          - name: "DEFAULT_VOLUME_SIZE"
            value: "2"
          - name: UBIQUITY_INSTANCE_NAME
            value: "instance1"
          - name: DEFAULT_FSTYPE
            value: "ext4"
          - name: SCBE_MANAGEMENT_IP
            value: "127.0.0.1"
          - name: SCBE_MANAGEMENT_PORT
            value: "8440"
          - name: SKIP_VERIFY_SSL
            value: "true"
          - name: SCBE_USERNAME
            value: "USER"
          - name: SCBE_PASSWORD
            value: "PASSWORD"
